name: Build and Deploy to Azure Container Apps

on:
  push:
    branches:
      - Main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Build the project
        run: |
          dotnet build ./SagaPlay-Backend/UserService/UserService.csproj --configuration Release
          dotnet build ./SagaPlay-Backend/CatalogService/CatalogService.csproj --configuration Release
          dotnet build ./SagaPlay-Backend/WatchlistService/WatchlistService.csproj --configuration Release
          dotnet build ./SagaPlay-Backend/RecommendationService/RecommendationService.csproj --configuration Release
          dotnet build ./SagaPlay-Backend/NotificationService/NotificationService.csproj --configuration Release
          dotnet build ./SagaPlay-Backend/ApiGateway/ApiGateway.csproj --configuration Release


      - name: Log in to Azure
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Log in to Azure Container Registry
        run: az acr login --name ${{ secrets.AZURE_CONTAINER_REGISTRY }}     
        
      - name: Build and push Docker images
        run: |
          declare -A services=(
            ["user-service"]="UserService"
            ["catalog-service"]="CatalogService"
            ["watchlist-service"]="WatchlistService"
            ["notification-service"]="NotificationService"
            ["recommendation-service"]="RecommendationService"
            ["apigateway-service"]="ApiGateway"
          )

          for svc in "${!services[@]}"; do
            echo "Building and pushing $svc..."
            docker build \
              -f SagaPlay-Backend/${services[$svc]}/Dockerfile \
              -t ${{ secrets.AZURE_CONTAINER_REGISTRY }}/$svc:latest \
              ./SagaPlay-Backend
            docker push ${{ secrets.AZURE_CONTAINER_REGISTRY }}/$svc:latest
          done
          
      - name: Deploy to Azure Container Apps
        uses: azure/cli@v2
        with:
          inlineScript: |
             declare -A services=(
              ["user-service"]="UserService"
              ["catalog-service"]="CatalogService"
              ["watchlist-service"]="WatchlistService"
              ["notification-service"]="NotificationService"
              ["recommendation-service"]="RecommendationService"
              ["apigateway-service"]="ApiGateway"
             )
              for svc in "${!services[@]}"; do
                echo "Deploying $svc..."
                if az containerapp show --name "$svc" --resource-group ${{ secrets.RESOURCE_GROUP }}  &>/dev/null; then
                    echo "Updating $svc..."
                    az containerapp update --name "$svc" --resource-group ${{ secrets.RESOURCE_GROUP }} --image ${{ secrets.AZURE_CONTAINER_REGISTRY }}/${services[$svc]}:latest
                 else
                    echo "Creating $svc..."
                    az containerapp create --name "$svc" --resource-group ${{ secrets.RESOURCE_GROUP }} --image ${{ secrets.AZURE_CONTAINER_REGISTRY }}/${services[$svc]}:latest --target-port 8080 --ingress internal --environment ${{ secrets.CONTAINER_APP_ENVIRONMENT}}
                  fi                  
              done
